### ISSUE TITLE
Amazon NL digital edition not working properly

### ISSUE THREAD

**Issue by trick0** [fpacenza/web_scraper#1]
Seems like charging station and ps5 digital edition share the same link.
I suggest to temporary remove this to avoid mail spam.
I've already tried to remove it and it works as it should

**Comment by fpacenza** [comment]
You are right! Sometimes Amazon shares the same links between consoles and accessories. I suggest to check the links at least every 2 days...

**Comment by trick0** [comment]
It would be quite useful to be able to change the configuration at runtime, gmail could not be too much happy with those emails endlessly spammed.
I've previously built a scraper with node js, your work here is written really well! 
Thanks for your attention :D

**Comment by fpacenza** [comment]
Yes, it would ne great... I will add the possibility ti change the configuration file as soon as possible
